version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
